### ISSUE TITLE
Managing our data

### ISSUE THREAD

**Issue by ttrine** [Rochester-NRT/AlphaGo#64]
We need a way to ensure that our data is organized, reliable, and consistent. This will become especially important as we begin training models. Right now I have a folder on an external hard drive that looks like this:
- models
- professional games
    - <.sgf games>
- self play
- training samples
    - 46x19x19
        - <.pkl training samples>

And that's pretty much it. To kick off the discussion, here's what I'm wondering about:
- Where can we host our data?
- Can we version control it?
    - If not, how can we keep things consistent across all contributors?
- Should we organize professional games by their database of origin? Or lump them all together in a flat directory structure?

**Comment by jtauber** [comment]
In terms of data hosting and version control, any reason not to just use GitHub? Possibly with https://git-lfs.github.com ?

**Comment by jtauber** [comment]
for SGF files, are there any existing conventions we could follow for extra-file metadata and directory structure?

**Comment by ttrine** [comment]
re your first comment, git lfs looks like it will probably suit our needs. Thanks!
re your second commend, there is nothing on the official sgf format website, but maybe there are some implicit conventions?

**Comment by jtauber** [comment]
Yeah, I'm not aware of any conventions but people who are used to archiving tens or hundreds of thousands of games might have some best practices.

**Comment by LetterRip** [comment]
You might have a look at

https://github.com/jmoudrik/deep-go-wrap

Looks like they are storing them in HDF format...

https://github.com/jmoudrik/deep-go-wrap

**Comment by wrongu** [comment]
I'd advocate for a few changes to the current organization and pipeline (see also #65):

* change from pkl to hdf5, as per @LetterRip's comment
* save a lot of training examples per file. Note that https://github.com/jmoudrik/deep-go-wrap and https://github.com/thouis/pyfuego both save the entire dataset to one file. Back-of-the-envelope, a dataset of 80K games at 200 moves per game gets to be >1TB of training data. Since this clearly won't fit into memory, we'll need to break the training data into multiple batches on the order of a few GB and be clever about how the training script samples from them (e.g. `game_converter` could handle randomizing the batches such that the training script simply trains on a full batch at once)
* have `game_converter` log which files have been processed so far so that it can be stopped and restarted. This info could maybe go in to the `metadata.json` file.
* make one more abstraction in `game_converter` so that it will process an iterable of files

We should also reconsider the option of saving each precomputed feature separately since feature preprocessing is turning out to be such a bottleneck. Once we've computed `board` and `liberties` for a dataset once, it would be nice to not have to recompute them for a new model that has `board`, `liberties`, _and_ `self_atari_size`, for example

**Comment by thouis** [comment]
I meant to mention in the other issue another plus of HDF5: disk-backed storage, similar to memory mapping.  So sampling from a very large file is possible without a lot of work.

Also, I tried to convert the entire KGS 6d+ set of games to HDF5 last night, but it crashed, I think because of too large a file.  Instead, I'm creating an HDF5 for every few thousand games, which I will then try to concatenate, or leave as separate files if that's not possible.

**Comment by wrongu** [comment]
I'm just [reading up on HDF5 now](docs.h5py.org/en/latest/high/dataset.html). I see why it's a good tool to use! I'm  surprised it crashed - the docs make it seem like using chunked storage, you should never run into memory issues.

Once you've processed KGS, would you consider sharing your dataset? It would allow us to start training the 'match' version of AlphaGo before finishing our own ladder features.

**Comment by thouis** [comment]
I think it may have been a filesystem issue, rather than HDF5-related.

I'd be happy to share the data.  I want to add a couple of things that will be useful for debugging, such as information about which game a move's data came from.

**Comment by thouis** [comment]
I've temporarily put a subset at 
https://s3.amazonaws.com/FuegoFeatures/kgs-19-2015-05-new.hdf5
https://s3.amazonaws.com/FuegoFeatures/KGS-2015_05-19-554-.tar.bz2

Before I try to share the whole thing, it would be good to make sure you can work with it (and there aren't any obvious bugs).

It doesn't seem to be compressing very well.  I'm not sure why that is, yet, but will look into it.

**Comment by AntreasAntoniou** [comment]
Also the s3 hosting is a really good idea because of the available tools. Especially the "sync" functionality that can check what has been changed and upload/download simultaneously to reach the current state.
